#!/bin/bash

source venv/bin/activate
export KLAYOUT_PYTHONPATH=${VIRTUAL_ENV}/lib/python3.12/site-packages:/home/juanjo/Projects/PD-PiC-Design/siepic_klayout_addon:/home/juanjo/Projects/PD-PiC-Design/PySpice
